# Generated by Django 2.2.3 on 2019-07-27 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lista',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
